[build]
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/orders-xyz123/*"
  to = "/kitchen.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"